### ISSUE TITLE
npm warnings

### ISSUE THREAD

**Issue by jpdevries** [oampo/thinkful-flappy-project#2]
noticed these on `npm install`

``` bash
npm WARN deprecated gulp-minify-css@0.3.13: Please use gulp-cssnano instead.
npm WARN deprecated lodash@1.0.2: lodash@<2.0.0 is no longer maintained. Upgrade to lodash@^3.0.0
```

**Comment by oampo** [comment]
This code isn't really ready for general consumption so I'll let it slide.  The repo is just up so I can point people at it if needs be.  In theory the course text should cover it.
